## START COPYRIGHT NOTICE ##
# Ansible-Python-Deploy-Role
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
## END COPYRIGHT NOTICE ##

# Debian or Ubuntu Distros

- name: "Update apt repo list | Debian or Ubuntu Distros"
  shell: "apt-get update"
  become: yes

# Python3
- name: "Install Python3 | Debian or Ubuntu Distros"
  shell: "apt-get install -y python3 python3-pip python3-virtualenv"
  become: yes
  ignore_errors: yes
  register: python3
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

# Python2
- name: "Install Python2 | Debian or Ubuntu Distros"
  shell: "apt-get install -y python python-pip python-virtualenv"
  become: yes
  ignore_errors: yes
  register: python2
  when:
    - auto_install_latest or (install_python2_only and not install_python3_only)