## START COPYRIGHT NOTICE ##
# Ansible-Python-Deploy-Role
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
## END COPYRIGHT NOTICE ##

# Red Hat 6 or CentOS 6 Distros

# Enable rh-amazon-rhui-client, enable rhui-REGION-rhel-server-extras|-optional, EPEL, and yum metadata clean
- name: "Ensure rh-amazon-rhui-client is installed | Red Hat 6 Distros"
  yum:
    name: rh-amazon-rhui-client
    state: latest
  become: yes
  when:
    - not ansible_facts['distribution']|lower == 'centos'
    - ansible_facts['os_family']|lower == 'redhat' or ansible_facts['distribution']|lower == 'red hat enterprise linux' or ansible_facts['distribution']|lower == 'red hat'

- name: "Ensure rhui-REGION-rhel-server-extras and -optional are enabled | Red Hat 6 Distros"
  shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras && yum-config-manager --enable rhui-REGION-rhel-server-optional"
  become: yes
  when:
    - not ansible_facts['distribution']|lower == 'centos'
    - ansible_facts['os_family']|lower == 'redhat' or ansible_facts['distribution']|lower == 'red hat enterprise linux' or ansible_facts['distribution']|lower == 'red hat'

- name: "Enable epel repo | Red Hat 6 or CentOS 6 Distros"
  yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    enabled: yes
  become: yes

- name: "yum-clean-metadata"
  command: yum clean metadata
  become: yes
  args:
    warn: no

# Python3
- name: "Install Python 3 | Red Hat 6 or CentOS 6 Distros"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python34
    - python34-setuptools
    - python34-libs
    - python34-devel
  register: python3
  ignore_errors: yes
  become: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Install Python 3 - pip | Red Hat 6 or CentOS 6 Distros"
  shell: "python3 easy_install.py pip"
  args:
    chdir: /usr/lib/python3.4/sites-packages/
  ignore_errors: yes
  become: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Upgrade Python 3 - pip | Red Hat 6 or CentOS 6 Distros"
  shell: "pip3 install --upgrade pip"
  args:
    chdir: /usr/lib/python3.4/sites-packages/
  ignore_errors: yes  
  become: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Upgrade Python 3 - pip --user | Red Hat 6 or CentOS 6 Distros"
  shell: "pip3 install --user --upgrade pip"
  args:
    chdir: /usr/lib/python3.4/sites-packages/
  ignore_errors: yes  
  become: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Python 3 - virtualenv - pip --user | Red Hat 6 or CentOS 6 Distros"
  shell: "pip3 install --upgrade virtualenv"
  args:
    chdir: /usr/lib/python3.4/sites-packages/
  ignore_errors: yes  
  become: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Python 3 - virtualenv - pip --user | Red Hat 6 or CentOS 6 Distros"
  shell: "pip3 install --user --upgrade virtualenv"
  args:
    chdir: /usr/lib/python3.4/sites-packages/
  ignore_errors: yes  
  become: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

# Python2
- name: "Install Python 2 | Red Hat 6 or CentOS 6 Distros"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python
    - python-pip
    - python-setuptools
    - python-libs
    - python-virtualenv
    - python-devel
  register: python2
  ignore_errors: yes
  become: yes
  when:
    - auto_install_latest or (install_python2_only and not install_python3_only)