## START COPYRIGHT NOTICE ##
# Ansible-Python-Deploy-Role
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
## END COPYRIGHT NOTICE ##

# Windows Server or Desktop Distros

- name: "Determine if CMA/McAfee agent is installed - masvc"
  win_service:
    name: masvc
  register: masvc_service

- name: "Determine if CMA/McAfee agent is installed - macmnsvc"
  win_service:
    name: macmnsvc
  register: macmnsvc_service

- name: "Retrieve the CMA/McAfee agent from ePO server"
  win_get_url:
    url: "{{ windows_url }}"
    validate_certs: "{{ validate_certs }}"
    dest: "{{ windows_dest }}"
  when:
    - masvc_service.state is not defined or not masvc_service.exists
    - macmnsvc_service.state is not defined or not macmnsvc_service.exists

- name: "Check that the CMA/McAfee agent is fully downloaded from ePO server"
  win_stat:
    path: "{{ windows_dest }}"
  register: windows_dest_file
#  when:
#    - masvc_service.state is not defined or not masvc_service.exists
#    - macmnsvc_service.state is not defined or not macmnsvc_service.exists

- name: "Install the CMA/McAfee agent"
  win_package:
    path: "{{ windows_dest }}"
    state: present
    product_id: "{{ windows_product_id }}"
  when:
    - windows_dest_file is defined and windows_dest_file.stat.exists
    - masvc_service.state is not defined or not masvc_service.exists
    - macmnsvc_service.state is not defined or not macmnsvc_service.exists

- name: "Remove the CMA/McAfee agent download"
  win_file:
    path: "{{ windows_dest }}"
    state: absent
  when:
    - windows_dest_file is defined and windows_dest_file.stat.exists
    - masvc_service.state is not defined or not masvc_service.exists
    - macmnsvc_service.state is not defined or not macmnsvc_service.exists
